sudo: required

services:
  - docker

env:
  global:
    - ANSIBLE_VERSION=latest
    - INVENTORY_DRIVER=local

before_install:
  - sudo docker pull ansible/ansible:${ANSIBLE_VERSION}
  
script:
  - docker run -ti -e ANSIBLE_CONFIG=/data/ansible.cfg -v .:/data -w /data ansible/ansible:${ANSIBLE_VERSION} "pip install -r requirements.txt && ansible-galaxy install -r requirements.ym
  - docker run -ti -e ANSIBLE_CONFIG=/data/ansible.cfg -v .:/data -w /data ansible/ansible:${ANSIBLE_VERSION} "pip install -r requirements.txt && ansible-playbook sites/${TRAVIS_BRANCH}"

notifications:
  email:
    - infrastructure@dallasmakerspace.org
